#!/bin/sh

case "$1" in
	-g) generation=$2; shift; shift ;;
	*)  generation= ;;
esac

copy() {
	if [ -n "$WAYLAND_DISPLAY" ]; then
		wl-copy
	else
		xclip -i
	fi
}

paste() {
	if [ -n "$WAYLAND_DISPLAY" ]; then
		wl-paste
	else
		xclip -o
	fi
}

case "$1" in
	'') url=`paste` ;;
	*)  url=$1      ;;
esac

pw=`cat ~/.sitepw`
host=${url#*//}
host=${host%%/*}
host=${host#*@}
host=${host%:*}
while :; do
	case "$host" in
		*.*.*)
			host=${host#*.}
			;;
		*)
			break
			;;
	esac
done

defaultgeneration=a1
f=$HOME/.sitepw.hosts/$host
if [ -z "$generation" ]; then
	generation=`cat "$f" 2>/dev/null`
fi
if [ -z "$generation" ]; then
	generation=$defaultgeneration
fi
echo "$generation" > "$f"
case "$generation" in
	0)
		opw=`echo "$host#$pw#$host#$pw#$host" | openssl sha1 -binary | openssl base64 -e | cut -c 1-12`
		;;
	[0-9]*)
		opw=`echo "$host" | openssl sha256 -hmac "$pw#$generation" -binary | openssl base64 -e | cut -c 1-12`
		;;
	a[0-9]*)
		opw=$(
			(
				len=12
				masterpwd=$pw
				site=$host
				generation=${generation#a}
				echo -n "$masterpwd" | argon2 "$site#$generation#0.2078795763507619085469556198349787700338778416317696080751358830554198772854821397886002778654260353" -id -r -t 1 -m 14 -p 1 -l $(((len+1)*3/4)) | perl -0777 -ne 'print pack "H*", $_' | openssl base64 -e | cut -c 1-$len
			)
		)
		;;
	# TODO: Parse options in the same form as the extension, and provide a
	# way to export all settings from the extension into a hosts directory.
esac

case "$1" in
	'')
		echo -n "$opw" | copy
		xmessage -timeout 2 -buttons OK "$host -> $opw"
		;;
	*)
		echo "$opw"
		;;
esac

